name: CI Pipeline

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: tug
          MYSQL_USER: mrtz
          MYSQL_PASSWORD: 3132820MRtz?
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

      redis:
        image: redis
        ports:
          - 6379:6379

    env:
      NODE_ENV: test
      DB_TYPE: sqlite
      DB_NAME: memory
      DB_SYNC: true
      REDIS_HOST: 127.0.0.1
      REDIS_PORT: 6379
      REDIS_TTL: 60
      APP_PORT: 3000

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Wait for MySQL to be ready
        run: |
          until mysql -h127.0.0.1 -umrtz -p'3132820MRtz?' -e 'SELECT 1'; do
            echo "Waiting for MySQL..."
            sleep 5
          done

      - name: Build the app
        run: npm run build


      - name: Run e2e tests
        run: npm run test:e2e
